### ISSUE TITLE
.env file setup

### ISSUE THREAD

**Issue by divincenzo** [adrian-casanova/disney_park_reservation_bot#3]
Step 1 in the Read Me says "create an .env file in the directory and enter the following". Was the info removed? I'm having difficulty running the bot and i think its because I don't have the .env file set up correctly.

After run.sh i get the following:

tokensCached:  false
Unable to get inputs

**Comment by cvn0va** [comment]
Hey I updated the readme so you can see what to put in the .env file but basically it should be:
email=email@mail.com
password=somepassword
date=2021-05-02

the date must be in the format YYYY-MM-DD

you must do that before you run the run.sh script.

**Comment by divincenzo** [comment]
> Hey I updated the readme so you can see what to put in the .env file but basically it should be:
> email=[email@mail.com](mailto:email@mail.com)
> password=somepassword
> date=2021-05-02
> 
> the date must be in the format YYYY-MM-DD
> 
> you must do that before you run the run.sh script.

It looks like the .env file was setup correctly. i still get the following error in terminal after running sh

```
TokensCached: false
Unable to get inputs

```
Chromium doesnt open either and I'm guessing this is why there is a token error. Any ideas where I may have gone wrong?
